version: "3.5"

volumes:
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: ./volumes/mysql

services:
  px_server:
    container_name: px_server
    build:
      context: ./build/
      args:
       - DB_LOGIN_A=px_user
       - DB_PASSWORD_A=px_pass
       - DB_NAME_A=px_base
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped